security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class:  AppBundle:User, property: username }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: ^/shares, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }